// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/bundle_service.proto

package bundle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bundle represents a group of transactions
type Bundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"` // Each transaction is serialized bytes
	Deadline      uint64                 `protobuf:"varint,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_proto_bundle_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundle_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_proto_bundle_service_proto_rawDescGZIP(), []int{0}
}

func (x *Bundle) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Bundle) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

// GetBundlesRequest is empty since we just want to fetch all available bundles
type GetBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundlesRequest) Reset() {
	*x = GetBundlesRequest{}
	mi := &file_proto_bundle_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundlesRequest) ProtoMessage() {}

func (x *GetBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundle_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundlesRequest.ProtoReflect.Descriptor instead.
func (*GetBundlesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bundle_service_proto_rawDescGZIP(), []int{1}
}

// GetBundlesResponse contains a list of bundles
type GetBundlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundles       []*Bundle              `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundlesResponse) Reset() {
	*x = GetBundlesResponse{}
	mi := &file_proto_bundle_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundlesResponse) ProtoMessage() {}

func (x *GetBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundle_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundlesResponse.ProtoReflect.Descriptor instead.
func (*GetBundlesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bundle_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBundlesResponse) GetBundles() []*Bundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

var File_proto_bundle_service_proto protoreflect.FileDescriptor

var file_proto_bundle_service_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x22, 0x48, 0x0a, 0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x13,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x62, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x07, 0x62, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x32, 0x56, 0x0a, 0x0d, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x73, 0x12, 0x19, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65,
	0x75, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_proto_bundle_service_proto_rawDescOnce sync.Once
	file_proto_bundle_service_proto_rawDescData []byte
)

func file_proto_bundle_service_proto_rawDescGZIP() []byte {
	file_proto_bundle_service_proto_rawDescOnce.Do(func() {
		file_proto_bundle_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bundle_service_proto_rawDesc), len(file_proto_bundle_service_proto_rawDesc)))
	})
	return file_proto_bundle_service_proto_rawDescData
}

var file_proto_bundle_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_bundle_service_proto_goTypes = []any{
	(*Bundle)(nil),             // 0: bundle.Bundle
	(*GetBundlesRequest)(nil),  // 1: bundle.GetBundlesRequest
	(*GetBundlesResponse)(nil), // 2: bundle.GetBundlesResponse
}
var file_proto_bundle_service_proto_depIdxs = []int32{
	0, // 0: bundle.GetBundlesResponse.bundles:type_name -> bundle.Bundle
	1, // 1: bundle.BundleService.GetBundles:input_type -> bundle.GetBundlesRequest
	2, // 2: bundle.BundleService.GetBundles:output_type -> bundle.GetBundlesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bundle_service_proto_init() }
func file_proto_bundle_service_proto_init() {
	if File_proto_bundle_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bundle_service_proto_rawDesc), len(file_proto_bundle_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bundle_service_proto_goTypes,
		DependencyIndexes: file_proto_bundle_service_proto_depIdxs,
		MessageInfos:      file_proto_bundle_service_proto_msgTypes,
	}.Build()
	File_proto_bundle_service_proto = out.File
	file_proto_bundle_service_proto_goTypes = nil
	file_proto_bundle_service_proto_depIdxs = nil
}
