// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/bundle_service.proto

package bundle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BundleService_GetBundles_FullMethodName = "/bundle.BundleService/GetBundles"
)

// BundleServiceClient is the client API for BundleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BundleService provides methods for retrieving transaction bundles
type BundleServiceClient interface {
	// GetBundles returns available transaction bundles
	GetBundles(ctx context.Context, in *GetBundlesRequest, opts ...grpc.CallOption) (*GetBundlesResponse, error)
}

type bundleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBundleServiceClient(cc grpc.ClientConnInterface) BundleServiceClient {
	return &bundleServiceClient{cc}
}

func (c *bundleServiceClient) GetBundles(ctx context.Context, in *GetBundlesRequest, opts ...grpc.CallOption) (*GetBundlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBundlesResponse)
	err := c.cc.Invoke(ctx, BundleService_GetBundles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BundleServiceServer is the server API for BundleService service.
// All implementations must embed UnimplementedBundleServiceServer
// for forward compatibility.
//
// BundleService provides methods for retrieving transaction bundles
type BundleServiceServer interface {
	// GetBundles returns available transaction bundles
	GetBundles(context.Context, *GetBundlesRequest) (*GetBundlesResponse, error)
	mustEmbedUnimplementedBundleServiceServer()
}

// UnimplementedBundleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBundleServiceServer struct{}

func (UnimplementedBundleServiceServer) GetBundles(context.Context, *GetBundlesRequest) (*GetBundlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBundles not implemented")
}
func (UnimplementedBundleServiceServer) mustEmbedUnimplementedBundleServiceServer() {}
func (UnimplementedBundleServiceServer) testEmbeddedByValue()                       {}

// UnsafeBundleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BundleServiceServer will
// result in compilation errors.
type UnsafeBundleServiceServer interface {
	mustEmbedUnimplementedBundleServiceServer()
}

func RegisterBundleServiceServer(s grpc.ServiceRegistrar, srv BundleServiceServer) {
	// If the following call pancis, it indicates UnimplementedBundleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BundleService_ServiceDesc, srv)
}

func _BundleService_GetBundles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BundleServiceServer).GetBundles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BundleService_GetBundles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BundleServiceServer).GetBundles(ctx, req.(*GetBundlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BundleService_ServiceDesc is the grpc.ServiceDesc for BundleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BundleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bundle.BundleService",
	HandlerType: (*BundleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBundles",
			Handler:    _BundleService_GetBundles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bundle_service.proto",
}
